(()=>{'use strict';
const $=s=>document.querySelector(s),KEY='dyAI-v12-history';
let history=[];try{const h=JSON.parse(sessionStorage.getItem(KEY)||'[]');if(Array.isArray(h))history=h.slice(-10)}catch{}
const subjects=[['ریاضی','ریاضی'],['هندسه','هندسه'],['فیزیک','فیزیک'],['شیمی','شیمی'],['فارسی','فارسی'],['عربی','عربی'],['زبان انگلیسی','زبان انگلیسی'],['دینی','دینی'],['جامعه‌شناسی','جامعه‌شناسی'],['تاریخ و جغرافیا','تاریخ و جغرافیا'],['نگارش','نگارش'],['تفکر و سواد دیجیتال','تفکر و سواد دیجیتال'],['عمومی','عمومی']];
function node(tag,cls,txt){const n=document.createElement(tag);if(cls)n.className=cls;if(txt!==undefined)n.textContent=txt;return n}
function mount(){if($('#dyAIOverlay'))return;
const b=node('button','dy-ai-open');b.id='dyAIOpen';b.type='button';b.setAttribute('aria-haspopup','dialog');b.append(node('span','', '✦'),node('b','','مهدی AI'),node('small','','دستیار درسی'));document.body.append(b);
const o=node('div','dy-ai-overlay');o.id='dyAIOverlay';o.setAttribute('aria-hidden','true');const modal=node('section','dy-ai-modal');modal.dir='rtl';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','dyAITitle');
const head=node('div','dy-ai-head'),intro=node('div'),close=node('button','dy-ai-x','×');close.id='dyAIClose';close.type='button';close.setAttribute('aria-label','بستن پنجره');intro.append(node('div','dy-ai-kicker','DEHOMYAR AI · V12'),node('h2','','مهدی AI ✦'),node('p','','معلم خصوصی، حل مرحله‌ای، بررسی پاسخ، تمرین‌ساز و خلاصه‌ساز برای درس‌های دهم.'));intro.lastChild.id='dyAITitle';head.append(intro,close);modal.append(head);
const tools=node('div','dy-ai-tools');[['teacher','👨‍🏫 معلم'],['solve','🧮 حل مسئله'],['check','✅ بررسی جواب'],['practice','📝 تمرین‌ساز'],['summary','📖 خلاصه درس']].forEach(([v,t])=>{const x=node('button','',t);x.type='button';x.dataset.mode=v;x.onclick=()=>{$('#dyAIMode').value=v;$('#dyAIInput').focus()};tools.append(x)});modal.append(tools);
const row=node('div','dy-ai-row'),sub=node('select'),mode=node('select');sub.id='dyAISubject';mode.id='dyAIMode';sub.setAttribute('aria-label','انتخاب درس');mode.setAttribute('aria-label','حالت پاسخ');subjects.forEach(([v,t])=>{const op=node('option','',t);op.value=v;sub.append(op)});[['teacher','معلم خصوصی'],['solve','حل مرحله‌ای'],['check','بررسی پاسخ'],['practice','تمرین‌ساز'],['summary','خلاصه درس']].forEach(([v,t])=>{const op=node('option','',t);op.value=v;mode.append(op)});row.append(sub,mode);modal.append(row);
const input=node('textarea');input.id='dyAIInput';input.rows=5;input.maxLength=8000;input.placeholder='سؤال یا متن درس را بنویس… (Ctrl+Enter برای ارسال)';input.setAttribute('aria-label','متن سؤال');modal.append(input);
const sample=node('div','dy-ai-samples');['دامنه تابع را توضیح بده','قانون دوم نیوتن با مثال','از این فصل ۳ تمرین بساز'].forEach(t=>{const x=node('button','',t);x.type='button';x.onclick=()=>{input.value=t;input.focus()};sample.append(x)});modal.append(sample);
const foot=node('div','dy-ai-foot'),status=node('span','','آماده‌ام 🚀');status.id='dyAIStatus';const send=node('button','','ارسال سؤال');send.id='dyAISend';send.type='button';foot.append(status,send);modal.append(foot);
const toolsRow=node('div','dy-ai-answer-tools'),copy=node('button','s','کپی آخرین پاسخ'),clear=node('button','s','پاک‌کردن گفتگو');copy.type=clear.type='button';copy.onclick=async()=>{const last=[...history].reverse().find(x=>x.role==='assistant');if(!last)return;try{await navigator.clipboard.writeText(last.content);status.textContent='پاسخ کپی شد ✓'}catch{status.textContent='کپی خودکار در دسترس نیست'}};clear.onclick=()=>{history=[];save();renderHistory();status.textContent='گفتگو پاک شد'};toolsRow.append(copy,clear);modal.append(toolsRow);
const transcript=node('div','dy-ai-conversation');transcript.id='dyAIConversation';transcript.setAttribute('aria-live','polite');transcript.setAttribute('aria-label','گفتگوی مهدی AI');modal.append(transcript);o.append(modal);document.body.append(o);
const open=()=>{o.classList.add('show');o.setAttribute('aria-hidden','false');setTimeout(()=>input.focus(),120)};const shut=()=>{o.classList.remove('show');o.setAttribute('aria-hidden','true');b.focus()};b.onclick=open;close.onclick=shut;o.addEventListener('click',e=>{if(e.target===o)shut()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&o.classList.contains('show'))shut()});send.onclick=sendQuestion;input.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')sendQuestion()});renderHistory();window.dyAISetSubject=name=>{const opt=[...sub.options].find(x=>x.value===name||x.textContent===name);if(opt)sub.value=opt.value;open()};window.addEventListener('dy12-open-ai',open)
}
function save(){try{sessionStorage.setItem(KEY,JSON.stringify(history.slice(-10)))}catch{}}
function renderHistory(){const box=$('#dyAIConversation');if(!box)return;box.replaceChildren();history.slice(-10).forEach(m=>{const card=node('article','dy-ai-message '+(m.role==='assistant'?'answer':'question'));card.append(node('b','',m.role==='assistant'?'مهدی AI':'شما'),node('p','',m.content));box.append(card)});box.scrollTop=box.scrollHeight}
async function sendQuestion(){const input=$('#dyAIInput'),status=$('#dyAIStatus'),btn=$('#dyAISend'),question=input.value.trim();if(!question){status.textContent='اول سؤال را بنویس 🙂';input.focus();return}if(question.length>8000){status.textContent='سؤال خیلی طولانی است؛ کوتاه‌ترش کن.';return}btn.disabled=true;status.textContent='در حال بررسی سؤال…';history.push({role:'user',content:question});renderHistory();save();try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({question,subject:$('#dyAISubject').value,mode:$('#dyAIMode').value,history:history.slice(-7,-1)})});const d=await r.json();if(!r.ok)throw new Error(d.error||'پاسخ دریافت نشد');const answer=String(d.answer||'پاسخی دریافت نشد.').slice(0,24000);history.push({role:'assistant',content:answer});history=history.slice(-10);save();renderHistory();status.textContent=d.local?'پاسخ محلی آماده شد · محدود':'پاسخ آماده شد ✓';input.value='';}catch(e){history.pop();renderHistory();save();status.textContent=e.message||'خطای ارتباط با AI'}finally{btn.disabled=false}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();