/* DahomYar Class Portal v1: accounts, private class spaces, representative publishing */
(()=>{'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TOKEN_KEY='dy-class-session-v1';let token=localStorage.getItem(TOKEN_KEY)||'',user=null,role='student',tab='login';
const classes=[['101','کلاس ۱۰۱'],['102','کلاس ۱۰۲'],['103','کلاس ۱۰۳'],['104','کلاس ۱۰۴']];
function cls(id){return (classes.find(x=>x[0]===String(id))||[String(id),'کلاس '+id])[1]}
async function api(path,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(token)headers.Authorization='Bearer '+token;const r=await fetch(path,{...opts,headers,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'خطا در ارتباط با سرور');return d}
function notice(text,bad=false){const el=$('#dycpMessage');if(el){el.textContent=text;el.className='dycp-message'+(bad?' bad':'')}}
function button(text,action,clsName=''){return '<button type="button" class="btn '+clsName+'" data-dycp="'+action+'">'+text+'</button>'}
function mount(){const nav=$('#nav'),main=$('.main');if(!nav||!main)return;
 if(!$('#dyClassPortal')){const p=document.createElement('section');p.id='dyClassPortal';p.className='page';p.innerHTML='<h1>👥 فضای اختصاصی کلاس</h1><p class="sub">حساب دانش‌آموز، تکالیف و اطلاعیه‌های مخصوص کلاس خودت.</p><div id="dycpRoot"></div>';main.append(p)}
 if(!nav.querySelector('[data-p="dyClassPortal"]')){const b=document.createElement('button');b.dataset.p='dyClassPortal';b.textContent='👥 کلاس من';b.addEventListener('click',()=>window.go?window.go('dyClassPortal'):(document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='dyClassPortal'))));nav.append(b)}
 render();if(token)loadMe();
}
function render(){const root=$('#dycpRoot');if(!root)return;
 if(!user){root.innerHTML='<div class="dycp-card"><div class="dycp-tabs">'+button('ورود دانش‌آموز','tab-login',tab==='login'?'s':'')+button('ثبت‌نام','tab-register',tab==='register'?'s':'')+button('ورود نماینده کلاس','tab-rep',tab==='rep'?'s':'')+'</div><div id="dycpMessage" class="dycp-message" role="status"></div>'+ (tab==='register'?'<form id="dycpForm" class="dycp-form"><label>نام نمایشی</label><input name="name" maxlength="80" required placeholder="مثلاً علی رضایی"><label>نام کاربری (انگلیسی)</label><input name="username" minlength="3" maxlength="24" pattern="[A-Za-z0-9_.-]{3,24}" required autocomplete="username" placeholder="ali_10"><label>رمز عبور (حداقل ۱۰ کاراکتر)</label><input name="password" type="password" minlength="10" maxlength="200" required autocomplete="new-password"><label>کلاس</label><select name="classId" required>'+classes.map(x=>'<option value="'+x[0]+'">'+x[1]+'</option>').join('')+'</select><button class="btn" type="submit">ساخت حساب</button><p class="dycp-muted">حساب و رمزت روی سرور ذخیره می‌شود؛ رمز به‌صورت هش امن نگهداری می‌شود.</p></form>':tab==='rep'?'<form id="dycpForm" class="dycp-form"><label>کلاس نمایندگی</label><select name="classId">'+classes.map(x=>'<option value="'+x[0]+'">'+x[1]+'</option>').join('')+'</select><label>کد اختصاصی نماینده</label><input name="code" required autocomplete="one-time-code" placeholder="کد تحویلی از مدیر اصلی"><button class="btn" type="submit">ورود به پنل نماینده</button><p class="dycp-muted">کد هر نماینده فقط برای همان کلاس معتبر است.</p></form>':'<form id="dycpForm" class="dycp-form"><label>نام کاربری</label><input name="username" required autocomplete="username"><label>رمز عبور</label><input name="password" type="password" required autocomplete="current-password"><button class="btn" type="submit">ورود به حساب</button></form>')+'</div><div class="dycp-card"><h3>🔐 مدیریت کدهای نمایندگان</h3><p class="dycp-muted">فقط مدیر اصلی سایت با نشست مدیریتی خودش می‌تواند کد اختصاصی کلاس‌ها را ایجاد یا تعویض کند.</p><label>توکن نشست مدیر اصلی</label><input id="dycpAdminToken" type="password" autocomplete="off" placeholder="توکن مدیریتی؛ با رمز عبور اشتباه نکن"><div class="dycp-row">'+button('نمایش وضعیت کدها','admin-list')+'</div><div id="dycpAdminOut"></div></div>';
 bind();return}
 const rep=role==='representative';
 root.innerHTML='<div class="dycp-card dycp-welcome"><div><span class="dycp-badge">'+(rep?'🛡️ پنل نماینده':'🎓 حساب دانش‌آموز')+'</span><h2>سلام '+esc(user.name||user.username)+'</h2><p>'+esc(cls(user.classId))+' · فضای جداگانه این کلاس</p></div>'+button('خروج','logout','s')+'</div><div id="dycpMessage" class="dycp-message" role="status"></div><div class="dycp-grid"><div class="dycp-card"><h3>📚 تکالیف کلاس</h3><div id="dycpHomework">در حال دریافت…</div></div><div class="dycp-card"><h3>📣 اطلاعیه‌های کلاس</h3><div id="dycpNews">در حال دریافت…</div></div></div>'+(rep?'<div class="dycp-card"><h2>📝 انتشار تکلیف</h2><form id="dycpHomeworkForm" class="dycp-form"><label>عنوان</label><input name="title" required maxlength="160"><label>درس</label><input name="subject" maxlength="80" placeholder="مثلاً ریاضی"><label>مهلت/تاریخ (اختیاری)</label><input name="date" maxlength="30" placeholder="مثلاً شنبه"><label>توضیحات</label><textarea name="body" required maxlength="10000" rows="4"></textarea><label>پیوست (اختیاری، PDF/عکس/Word تا ۸ مگابایت)</label><input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.doc,.docx"><button class="btn" type="submit">انتشار برای '+esc(cls(user.classId))+'</button></form></div><div class="dycp-card"><h2>📣 انتشار اطلاعیه</h2><form id="dycpNewsForm" class="dycp-form"><label>عنوان</label><input name="title" required maxlength="180"><label>متن اطلاعیه</label><textarea name="body" required maxlength="10000" rows="4"></textarea><button class="btn" type="submit">انتشار اطلاعیه برای همین کلاس</button></form></div>':'')+'<p class="dycp-muted">🔒 این فضا فقط به حساب‌های عضو همین کلاس دسترسی می‌دهد. تکالیف و اطلاعیه‌های کلاس‌های دیگر از این پنل قابل مشاهده یا انتشار نیستند.</p>';
 bind();loadContent();
}
function bind(){
 document.querySelectorAll('[data-dycp]').forEach(b=>b.addEventListener('click',()=>act(b.dataset.dycp)));
 const form=$('#dycpForm');if(form)form.addEventListener('submit',submitAuth);
 const hf=$('#dycpHomeworkForm');if(hf)hf.addEventListener('submit',e=>publish(e,'/api/class/homework'));
 const nf=$('#dycpNewsForm');if(nf)nf.addEventListener('submit',e=>publish(e,'/api/class/announcements'));
}
function act(a){if(a==='tab-login'||a==='tab-register'||a==='tab-rep'){tab=a.slice(4);render()}else if(a==='logout')logout();else if(a==='admin-list')adminList()}
async function submitAuth(e){e.preventDefault();const f=new FormData(e.currentTarget),d=Object.fromEntries(f.entries());try{
 let out;if(tab==='register')out=await api('/api/account/register',{method:'POST',body:JSON.stringify(d)});else if(tab==='rep')out=await api('/api/class/representative/login',{method:'POST',body:JSON.stringify(d)});else out=await api('/api/account/login',{method:'POST',body:JSON.stringify(d)});
 token=out.token;localStorage.setItem(TOKEN_KEY,token);user=out.user;role=out.role||'student';render();
 }catch(err){notice(err.message,true)}}
async function loadMe(){try{const d=await api('/api/account/me');user=d.user;role=d.role;render()}catch{token='';localStorage.removeItem(TOKEN_KEY);user=null;role='student';render()}}
async function logout(){try{await api('/api/account/logout',{method:'POST',body:'{}'})}catch{}token='';user=null;role='student';localStorage.removeItem(TOKEN_KEY);render()}
function cards(items,news=false){if(!items.length)return '<p class="dycp-muted">هنوز موردی برای این کلاس ثبت نشده است.</p>';return items.map(x=>'<article class="dycp-item"><div class="dycp-badge">'+(news?'📣 اطلاعیه':'📘 '+esc(x.subject||'عمومی'))+'</div><h3>'+esc(x.title)+'</h3><p>'+esc(x.body)+'</p>'+(!news&&x.file?'<p><a class="btn s" href="'+esc(x.file)+'" target="_blank" rel="noopener">📎 دریافت پیوست</a></p>':'')+'<small>'+esc(x.date||new Date(x.createdAt||Date.now()).toLocaleDateString('fa-IR'))+'</small></article>').join('')}
async function loadContent(){if(!user||!token)return;try{const [h,n]=await Promise.all([api('/api/class/homework'),api('/api/class/announcements')]);const hw=$('#dycpHomework'),nw=$('#dycpNews');if(hw)hw.innerHTML=cards(h.items||[]);if(nw)nw.innerHTML=cards(n.items||[],true)}catch(e){notice(e.message,true)}}
async function publish(e,path){e.preventDefault();const form=e.currentTarget,f=new FormData(form),d={};for(const [k,v] of f.entries()){if(k==='file'){if(v&&v.size){if(v.size>8*1024*1024){notice('حجم فایل باید کمتر از ۸ مگابایت باشد.',true);return}d.file={name:v.name,data:await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(Error('خواندن فایل ناموفق بود'));r.readAsDataURL(v)})}}}else d[k]=v}try{await api(path,{method:'POST',body:JSON.stringify(d)});form.reset();notice('با موفقیت برای '+cls(user.classId)+' منتشر شد.');loadContent()}catch(err){notice(err.message,true)}}
async function adminList(){const out=$('#dycpAdminOut'),t=$('#dycpAdminToken')?.value.trim();if(!out)return;if(!t){out.textContent='توکن مدیر اصلی را وارد کن.';return}try{const r=await fetch('/api/admin/class-codes',{headers:{Authorization:'Bearer '+t},cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'دسترسی رد شد');out.innerHTML='<div class="dycp-code-grid">'+d.classes.map(c=>'<div class="dycp-code"><b>'+esc(cls(c.classId))+'</b><p>'+ (c.hasCode?'کد قبلاً ساخته شده':'هنوز کدی ساخته نشده')+'</p><button type="button" class="btn s" data-dycp-generate="'+c.classId+'">'+(c.hasCode?'تعویض کد':'ساخت کد')+'</button></div>').join('')+'</div><div id="dycpNewCode" class="dycp-message"></div>';out.querySelectorAll('[data-dycp-generate]').forEach(b=>b.addEventListener('click',()=>generateCode(t,b.dataset.dycpGenerate)))}catch(e){out.textContent=e.message}}
async function generateCode(t,classId){if(!confirm('کد نماینده '+cls(classId)+' ساخته/تعویض شود؟ کد قبلی بلافاصله باطل می‌شود.'))return;const out=$('#dycpNewCode');try{const r=await fetch('/api/admin/class-codes',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({classId})});const d=await r.json();if(!r.ok)throw Error(d.error||'خطا');out.textContent='کد جدید '+cls(classId)+': '+d.code+' — همین حالا آن را امن کپی کن؛ بعداً دوباره نمایش داده نمی‌شود.'}catch(e){if(out)out.textContent=e.message}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();