const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url'),child_process=require('child_process');
const AdmZip=require('adm-zip');
const aiRoute=require('./ai-route');
const ROOT=__dirname, DATA=process.env.DATA_DIR ? path.resolve(process.env.DATA_DIR) : path.join(ROOT,'data'), UP=path.join(DATA,'uploads');
fs.mkdirSync(UP,{recursive:true});
const DB=path.join(DATA,'homework.json'); if(!fs.existsSync(DB))fs.writeFileSync(DB,'[]');
const NEWS=path.join(DATA,'news.json'); if(!fs.existsSync(NEWS))fs.writeFileSync(NEWS,'[]');
const SETTINGS=path.join(DATA,'site-settings.json'); if(!fs.existsSync(SETTINGS))fs.writeFileSync(SETTINGS,JSON.stringify({version:'10.0.0',announcement:'',siteTitle:'دهم‌یار',siteSubtitle:'همراه هوشمند پایه دهم',maintenance:false,updatedAt:Date.now()},null,2));
const STATS=path.join(DATA,'stats.json'); if(!fs.existsSync(STATS))fs.writeFileSync(STATS,JSON.stringify({total:0,today:0,lastDay:new Date().toISOString().slice(0,10)},null,2));
const RELEASE=path.join(DATA,'dehomyar-latest.zip');
const RELEASES=path.join(DATA,'releases'); const CURRENT=path.join(DATA,'current'); fs.mkdirSync(RELEASES,{recursive:true}); fs.mkdirSync(CURRENT,{recursive:true});
const ADMIN_FILE=path.join(DATA,'admin.json');
const sessions=new Map(), loginFails=new Map();
const DEFAULT_USER=process.env.ADMIN_USER || 'mahdinava89nava', DEFAULT_PASS=process.env.ADMIN_PASSWORD || '';
if(!DEFAULT_PASS){console.error('ADMIN_PASSWORD is required on first startup'); process.exit(1)}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(password,salt,64).toString('hex');return {salt,hash}}
function verifyPassword(password,record){try{return crypto.timingSafeEqual(Buffer.from(hashPassword(password,record.salt).hash,'hex'),Buffer.from(record.hash,'hex'))}catch{return false}}
if(!fs.existsSync(ADMIN_FILE)){const h=hashPassword(DEFAULT_PASS);writeJson(ADMIN_FILE,{username:DEFAULT_USER,salt:h.salt,hash:h.hash,createdAt:Date.now()})}
function adminConfig(){return readJson(ADMIN_FILE,{username:DEFAULT_USER,salt:'',hash:''})}
function read(){const value=readJson(DB,[]);if(Array.isArray(value))return value;console.error('[storage] homework.json is not an array; trying backup');const backup=readJson(DB+'.bak',null);return Array.isArray(backup)?backup:[]}
function write(x){if(!Array.isArray(x))throw new Error('Homework data must be an array');writeJson(DB,x)}
function readJson(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch(e){if(!(e&&e.code==='ENOENT'))console.error('[storage] Failed reading '+path.basename(file)+': '+(e.message||e));try{const backup=file+'.bak';if(fs.existsSync(backup)){const value=JSON.parse(fs.readFileSync(backup,'utf8'));console.warn('[storage] Recovered '+path.basename(file)+' from backup');return value}}catch(b){console.error('[storage] Backup recovery failed for '+path.basename(file)+': '+(b.message||b))}return fallback}}
function writeJson(file,x){const tmp=file+'.tmp-'+process.pid+'-'+Date.now();try{fs.writeFileSync(tmp,JSON.stringify(x,null,2));if(fs.existsSync(file)){try{JSON.parse(fs.readFileSync(file,'utf8'));fs.copyFileSync(file,file+'.bak')}catch(e){console.error('[storage] Existing '+path.basename(file)+' is invalid; keeping previous backup')}}fs.renameSync(tmp,file)}catch(e){try{fs.rmSync(tmp,{force:true})}catch(_){}throw e}}
function bumpStats(){const x=readJson(STATS,{total:0,today:0,lastDay:''});const d=new Date().toISOString().slice(0,10);if(x.lastDay!==d){x.today=0;x.lastDay=d}x.total++;x.today++;writeJson(STATS,x);return x}
function settings(){return readJson(SETTINGS,{version:'10.0.0',announcement:'',siteTitle:'دهم‌یار',siteSubtitle:'همراه هوشمند پایه دهم',maintenance:false,updatedAt:Date.now()})}
function news(){return readJson(NEWS,[])} function writeNews(x){writeJson(NEWS,x)}
function safeReleaseEntries(zip){const allowed=/^(index\.html|manifest\.json|service-worker\.js|offline\.html|icons\/(icon-192\.png|icon-512\.png))$/;return zip.getEntries().filter(e=>!e.isDirectory()).map(e=>e.entryName.replace(/\\/g,'/')).filter(n=>allowed.test(n))}
function installRelease(zipBuf,version){
 const zip=new AdmZip(zipBuf); const names=safeReleaseEntries(zip);
 if(!names.includes('index.html')||!names.includes('service-worker.js'))throw new Error('فایل آپدیت باید index.html و service-worker.js داشته باشد');
 const tmp=path.join(DATA,'release-'+Date.now());fs.mkdirSync(tmp,{recursive:true});
 try{
   for(const n of names){const dest=path.join(tmp,n);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,zip.readFile(n))}
   const next=path.join(DATA,'current-next-'+Date.now());fs.mkdirSync(next,{recursive:true});
   for(const n of names){const dest=path.join(next,n);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(tmp,n),dest)}
   if(fs.existsSync(CURRENT))fs.rmSync(CURRENT,{recursive:true,force:true});
   fs.renameSync(next,CURRENT);
   if(fs.existsSync(RELEASE)) fs.copyFileSync(RELEASE,path.join(RELEASES,(settings().version||'unknown').replace(/[^a-zA-Z0-9._-]/g,'_')+'-'+Date.now()+'.zip'));
   fs.writeFileSync(RELEASE,zipBuf);
   const st=settings();st.version=String(version||st.version||'8.0.0').slice(0,30);st.updatedAt=Date.now();writeJson(SETTINGS,st);
 }finally{fs.rmSync(tmp,{recursive:true,force:true})}
}
function json(res,code,obj){const b=JSON.stringify(obj);res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(b)}
function body(req){return new Promise((resolve,reject)=>{let s='';let n=0;req.on('data',c=>{n+=c.length;if(n>12e6){req.destroy();reject(new Error('حجم درخواست زیاد است'))}else s+=c});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return false;const t=h.slice(7),exp=sessions.get(t);if(!exp)return false;if(exp<Date.now()){sessions.delete(t);return false}return true}
function clientKey(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim()}
function security(res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(),microphone=(),geolocation=()')}

const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.json':'application/json','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.pdf':'application/pdf','.doc':'application/msword','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'};
const server=http.createServer(async(req,res)=>{try{security(res); const u=url.parse(req.url,true); if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS'});return res.end()}
if(u.pathname==='/api/ai'&&req.method==='POST'){return aiRoute(req,res,body,json)}
if(u.pathname==='/api/homework'&&req.method==='GET'){const items=read().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)); res.setHeader('X-DH-Data-Count',String(items.length)); res.setHeader('X-DH-Server-Time',String(Date.now())); console.log('[API] GET /api/homework -> '+items.length+' items'); return json(res,200,{items})}
if(u.pathname==='/api/news'&&req.method==='GET'){return json(res,200,{items:news().filter(x=>x.published!==false).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,30),settings:settings()})}
if(u.pathname==='/api/update'&&req.method==='GET'){return json(res,200,{version:settings().version,announcement:settings().announcement||'',updatedAt:settings().updatedAt||0,hasPackage:fs.existsSync(RELEASE)})}
if(u.pathname==='/api/stats'&&req.method==='GET'){return json(res,200,readJson(STATS,{total:0,today:0,lastDay:''}))}
if(u.pathname==='/api/update/download'&&req.method==='GET'){if(!fs.existsSync(RELEASE))return json(res,404,{error:'نسخه‌ای برای دانلود وجود ندارد'});res.writeHead(200,{'Content-Type':'application/zip','Content-Disposition':'attachment; filename="dehomyar-update.zip"','Cache-Control':'no-store'});return fs.createReadStream(RELEASE).pipe(res)}
if(u.pathname==='/api/admin/settings'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});return json(res,200,{settings:settings(),stats:readJson(STATS,{})})}
if(u.pathname==='/api/admin/settings'&&req.method==='POST'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const x=await body(req),st=settings();st.announcement=String(x.announcement??st.announcement).slice(0,4000);st.siteTitle=String(x.siteTitle??st.siteTitle).slice(0,120);st.siteSubtitle=String(x.siteSubtitle??st.siteSubtitle).slice(0,240);st.maintenance=!!x.maintenance;writeJson(SETTINGS,st);return json(res,200,{settings:st})}
if(u.pathname==='/api/admin/debug'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const stat=f=>{try{const s=fs.statSync(f);return {exists:true,size:s.size,modifiedAt:s.mtime.toISOString()}}catch{return {exists:false}}};return json(res,200,{dataDir:DATA,db:DB,items:read().length,homeworkFile:stat(DB),homeworkBackup:stat(DB+'.bak'),newsFile:stat(NEWS),settingsFile:stat(SETTINGS),dataDirConfigured:!!process.env.DATA_DIR,hostname:require('os').hostname(),pid:process.pid,node:process.version,uptime:process.uptime()})}
if(u.pathname==='/api/admin/status'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const st=settings();return json(res,200,{ok:true,version:st.version,uptime:process.uptime(),node:process.version,online:true})}
if(u.pathname==='/api/admin/password'&&req.method==='POST'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const x=await body(req);if(!x.current||!x.next||String(x.next).length<10)return json(res,400,{error:'رمز جدید باید حداقل ۱۰ کاراکتر باشد'});const cfg=adminConfig();if(!verifyPassword(String(x.current),cfg))return json(res,403,{error:'رمز فعلی اشتباه است'});const h=hashPassword(String(x.next));writeJson(ADMIN_FILE,{username:cfg.username,salt:h.salt,hash:h.hash,createdAt:cfg.createdAt,updatedAt:Date.now()});sessions.clear();return json(res,200,{ok:true})}
if(u.pathname==='/api/admin/backup/restore'&&req.method==='POST'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const x=await body(req);if(!x.data)return json(res,400,{error:'پشتیبان لازم است'});try{const d=JSON.parse(String(x.data));if(!Array.isArray(d.homework)||!Array.isArray(d.news)||!d.settings)throw new Error('ساختار پشتیبان معتبر نیست');write(d.homework.slice(0,500));writeNews(d.news.slice(0,500));writeJson(SETTINGS,{...settings(),...d.settings,updatedAt:Date.now()});return json(res,200,{ok:true})}catch(e){return json(res,400,{error:e.message||'پشتیبان نامعتبر است'})}}
if(u.pathname==='/api/news/admin'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});return json(res,200,{items:news().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))})}
if(u.pathname==='/api/news'&&req.method==='POST'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const x=await body(req);if(!x.title||!x.body)return json(res,400,{error:'عنوان و متن خبر لازم است'});const a=news(); if(x.id){const i=a.findIndex(n=>n.id===String(x.id)); if(i<0)return json(res,404,{error:'پیدا نشد'}); a[i]={...a[i],title:String(x.title).slice(0,180),body:String(x.body).slice(0,10000),date:String(x.date||'').slice(0,30),type:String(x.type||'خبر').slice(0,30),published:x.published!==false,updatedAt:Date.now()};writeNews(a);return json(res,200,{item:a[i]})} const item={id:crypto.randomBytes(10).toString('hex'),title:String(x.title).slice(0,180),body:String(x.body).slice(0,10000),date:String(x.date||'').slice(0,30),type:String(x.type||'خبر').slice(0,30),published:x.published!==false,createdAt:Date.now()};a.push(item);writeNews(a);return json(res,201,{item})}
if(u.pathname.startsWith('/api/news/')&&req.method==='DELETE'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const id=u.pathname.split('/').pop(),a=news();if(!a.some(x=>x.id===id))return json(res,404,{error:'پیدا نشد'});writeNews(a.filter(x=>x.id!==id));return json(res,200,{ok:true})}
if(u.pathname==='/api/admin/releases'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const items=fs.readdirSync(RELEASES).filter(x=>x.endsWith('.zip')).sort().reverse().slice(0,20).map(x=>({file:x}));return json(res,200,{items})}
if(u.pathname==='/api/admin/backup'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const pack={exportedAt:new Date().toISOString(),settings:settings(),homework:read(),news:news()};return json(res,200,pack)}
if(u.pathname==='/api/admin/update'&&req.method==='POST'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const x=await body(req);if(!x.data||!String(x.data).startsWith('data:application/zip;base64,'))return json(res,400,{error:'فایل ZIP معتبر لازم است'});try{const buf=Buffer.from(String(x.data).split(',')[1],'base64');if(buf.length>25*1024*1024)return json(res,400,{error:'حجم بسته بیشتر از ۲۵ مگابایت است'});installRelease(buf,x.version);return json(res,200,{ok:true,version:settings().version})}catch(e){return json(res,400,{error:e.message||'آپدیت نامعتبر است'})}}
if(u.pathname==='/api/admin/login'&&req.method==='POST'){const key=clientKey(req),now=Date.now(),f=loginFails.get(key)||{count:0,until:0};if(f.until>now)return json(res,429,{error:'تعداد تلاش‌ها زیاد است؛ چند دقیقه بعد دوباره امتحان کن'});const x=await body(req),cfg=adminConfig();if(x.username!==cfg.username||!verifyPassword(String(x.password||''),cfg)){f.count++;if(f.count>=6){f.until=now+10*60*1000;f.count=0}loginFails.set(key,f);return json(res,401,{error:'نام کاربری یا رمز عبور اشتباه است'})}loginFails.delete(key);const t=crypto.randomBytes(32).toString('hex');sessions.set(t,Date.now()+12*60*60*1000);return json(res,200,{token:t})}
if(u.pathname==='/api/homework/admin'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});return json(res,200,{items:read().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))})}
if(u.pathname==='/api/homework'&&req.method==='POST'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const x=await body(req);if(!x.title||!x.body)return json(res,400,{error:'عنوان و متن تکلیف لازم است'});let file=null;if(x.file?.data){if(!/^data:[\w/+.-]+;base64,/.test(x.file.data))return json(res,400,{error:'فایل نامعتبر است'});const ext=path.extname(x.file.name||'').toLowerCase();if(!['.pdf','.png','.jpg','.jpeg','.webp','.doc','.docx'].includes(ext))return json(res,400,{error:'نوع فایل مجاز نیست'});const id=crypto.randomBytes(8).toString('hex');const fn=id+ext;fs.writeFileSync(path.join(UP,fn),Buffer.from(x.file.data.split(',')[1],'base64'));file='/uploads/'+fn}
const a=read(); if(x.id){const i=a.findIndex(h=>h.id===String(x.id)); if(i<0)return json(res,404,{error:'پیدا نشد'}); if(file&&a[i].file)try{fs.unlinkSync(path.join(UP,path.basename(a[i].file)))}catch{}; a[i]={...a[i],title:String(x.title).slice(0,160),subject:String(x.subject||'عمومی').slice(0,80),date:String(x.date||'').slice(0,30),body:String(x.body).slice(0,10000),file:file||a[i].file,updatedAt:Date.now()};write(a);return json(res,200,{item:a[i]})} const item={id:crypto.randomBytes(10).toString('hex'),title:String(x.title).slice(0,160),subject:String(x.subject||'عمومی').slice(0,80),date:String(x.date||'').slice(0,30),body:String(x.body).slice(0,10000),file,createdAt:Date.now()};a.push(item);write(a);return json(res,201,{item})}
if(u.pathname.startsWith('/api/homework/')&&req.method==='DELETE'){if(!auth(req))return json(res,401,{error:'نیاز به ورود مدیر'});const id=u.pathname.split('/').pop();const a=read();const item=a.find(x=>x.id===id);if(!item)return json(res,404,{error:'پیدا نشد'});if(item.file)try{fs.unlinkSync(path.join(UP,path.basename(item.file)))}catch{};write(a.filter(x=>x.id!==id));return json(res,200,{ok:true})}
if(u.pathname.startsWith('/uploads/')&&req.method==='GET'){const name=path.basename(decodeURIComponent(u.pathname.slice('/uploads/'.length)));const uploadPath=path.join(UP,name);if(name&&uploadPath.startsWith(UP+path.sep)&&fs.existsSync(uploadPath)&&fs.statSync(uploadPath).isFile()){res.writeHead(200,{'Content-Type':mime[path.extname(uploadPath).toLowerCase()]||'application/octet-stream','Cache-Control':'private, max-age=300','X-Content-Type-Options':'nosniff'});return fs.createReadStream(uploadPath).pipe(res)}}
if(u.pathname==='/admin'||u.pathname==='/admin/')u.pathname='/index.html';
const relPath=(u.pathname==='/'?'/index.html':u.pathname); let filePath=path.normalize(path.join(CURRENT,relPath)); if(!filePath.startsWith(CURRENT))return json(res,403,{error:'forbidden'}); if(!(fs.existsSync(filePath)&&fs.statSync(filePath).isFile())){filePath=path.normalize(path.join(ROOT,relPath)); if(!filePath.startsWith(ROOT))return json(res,403,{error:'forbidden'})} if(fs.existsSync(filePath)&&fs.statSync(filePath).isFile()){if(u.pathname==='/'||u.pathname==='/index.html')bumpStats();res.writeHead(200,{'Content-Type':mime[path.extname(filePath).toLowerCase()]||'application/octet-stream','Cache-Control':u.pathname==='/'||u.pathname==='/index.html'?'no-cache':'public, max-age=3600'});return fs.createReadStream(filePath).pipe(res)}return json(res,404,{error:'not found'});
}catch(e){console.error(e);json(res,500,{error:'خطای سرور'})}});
const PORT=process.env.PORT||3000;server.listen(PORT,()=>{console.log('DehomYar running on http://localhost:'+PORT);console.log('[storage] DATA_DIR='+DATA+' configured='+!!process.env.DATA_DIR+' homeworkExists='+fs.existsSync(DB)+' backupExists='+fs.existsSync(DB+'.bak'));});
